services:
  - type: web
    name: travelnow-app-v3
    env: node
    autoDeploy: true
    buildCommand: npm ci && npm run build && npm ci --prefix backend
    startCommand: node backend/src/server.js
    healthCheckPath: /health
    envVars:
      - key: VITE_BASE_PATH
        value: /
      - key: MONGODB_URI
        sync: false
